# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Espresso(object):
    def setupUi(self, Espresso):
        Espresso.setObjectName("Espresso")
        Espresso.resize(1051, 689)
        self.centralwidget = QtWidgets.QWidget(parent=Espresso)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 10, 1011, 661))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_btn = QtWidgets.QPushButton(parent=self.widget)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout.addWidget(self.add_btn)
        self.edit_btn = QtWidgets.QPushButton(parent=self.widget)
        self.edit_btn.setObjectName("edit_btn")
        self.horizontalLayout.addWidget(self.edit_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableCoffee = QtWidgets.QTableWidget(parent=self.widget)
        self.tableCoffee.setObjectName("tableCoffee")
        self.tableCoffee.setColumnCount(7)
        self.tableCoffee.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableCoffee.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCoffee.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCoffee.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCoffee.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCoffee.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCoffee.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCoffee.setHorizontalHeaderItem(6, item)
        self.tableCoffee.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tableCoffee)
        Espresso.setCentralWidget(self.centralwidget)

        self.retranslateUi(Espresso)
        QtCore.QMetaObject.connectSlotsByName(Espresso)

    def retranslateUi(self, Espresso):
        _translate = QtCore.QCoreApplication.translate
        Espresso.setWindowTitle(_translate("Espresso", "Эспрессо"))
        self.add_btn.setText(_translate("Espresso", "Добавить новую запись"))
        self.edit_btn.setText(_translate("Espresso", "Изменить запись"))
        item = self.tableCoffee.horizontalHeaderItem(0)
        item.setText(_translate("Espresso", "ID"))
        item = self.tableCoffee.horizontalHeaderItem(1)
        item.setText(_translate("Espresso", "Сорт"))
        item = self.tableCoffee.horizontalHeaderItem(2)
        item.setText(_translate("Espresso", "Степень обжарки"))
        item = self.tableCoffee.horizontalHeaderItem(3)
        item.setText(_translate("Espresso", "Молотый/зерно"))
        item = self.tableCoffee.horizontalHeaderItem(4)
        item.setText(_translate("Espresso", "Описание вкуса"))
        item = self.tableCoffee.horizontalHeaderItem(5)
        item.setText(_translate("Espresso", "Цена"))
        item = self.tableCoffee.horizontalHeaderItem(6)
        item.setText(_translate("Espresso", "Объем упаковки"))
